const JournalEntry = require('../models/JournalEntry');
const { CHART_OF_ACCOUNTS, getAccount, DEFAULT_ACCOUNTS } = require('../constants/chartOfAccounts');

/**
 * Journal Entry Service
 * Handles automatic creation of journal entries for all financial transactions
 */

class JournalService {
  /**
   * Create a journal entry with multiple lines
   * Ensures debits equal credits
   */
  static async createEntry(companyId, userId, options) {
    const {
      date = new Date(),
      description,
      sourceType = 'manual',
      sourceId = null,
      sourceReference = null,
      lines = [],
      isAutoGenerated = false,
      notes = ''
    } = options;

    // Normalize and validate companyId/userId
    if (userId && typeof userId === 'object' && userId._id) userId = userId._id;
    if (!companyId) throw new Error('Missing companyId when creating journal entry');
    if (!userId) throw new Error('Missing userId when creating journal entry');

    // Validate lines
    if (lines.length < 2) {
      throw new Error('Journal entry must have at least 2 lines');
    }

    // Calculate totals
    const totalDebit = lines.reduce((sum, line) => sum + (line.debit || 0), 0);
    const totalCredit = lines.reduce((sum, line) => sum + (line.credit || 0), 0);

    // Validate balance
    if (Math.abs(totalDebit - totalCredit) > 0.01) {
      throw new Error(`Journal entry is not balanced. Debits: ${totalDebit}, Credits: ${totalCredit}`);
    }

    // Generate entry number
    const entryNumber = await JournalEntry.generateEntryNumber(companyId);

    // Create entry
    let entry;
    try {
      entry = await JournalEntry.create({
      company: companyId,
      entryNumber,
      date,
      description,
      sourceType,
      sourceId,
      sourceReference,
      lines,
      totalDebit,
      totalCredit,
      isAutoGenerated,
      createdBy: userId,
      postedBy: userId,
      status: 'posted',
      notes
      });
    } catch (err) {
      const enhanced = new Error(`JournalService.createEntry failed: ${err.message}`);
      enhanced.cause = err;
      throw enhanced;
    }

    return entry;
  }

  /**
   * Add a single debit line
   */
  static createDebitLine(accountCode, amount, description = '', reference = '') {
    const account = getAccount(accountCode);
    return {
      accountCode,
      accountName: account?.name || 'Unknown Account',
      description,
      debit: amount || 0,
      credit: 0,
      reference
    };
  }

  /**
   * Add a single credit line
   */
  static createCreditLine(accountCode, amount, description = '', reference = '') {
    const account = getAccount(accountCode);
    return {
      accountCode,
      accountName: account?.name || 'Unknown Account',
      description,
      debit: 0,
      credit: amount || 0,
      reference
    };
  }

  // =====================================================
  // SALES TRANSACTIONS
  // =====================================================

  /**
   * Invoice created (on credit)
   * Debit: Accounts Receivable
   * Credit: Sales Revenue + VAT
   */
  static async createInvoiceEntry(companyId, userId, invoice) {
    const lines = [];
    const total = invoice.total || 0;
    const vatAmount = invoice.vatAmount || 0;
    const subtotal = total - vatAmount;

    // Debit: Accounts Receivable
    lines.push(this.createDebitLine(
      DEFAULT_ACCOUNTS.accountsReceivable,
      total,
      `Invoice ${invoice.invoiceNumber} - Receivable`
    ));

    // Credit: Sales Revenue
    if (subtotal > 0) {
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.salesRevenue,
        subtotal,
        `Invoice ${invoice.invoiceNumber} - Revenue`
      ));
    }

    // Credit: VAT Payable
    if (vatAmount > 0) {
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.vatPayable,
        vatAmount,
        `Invoice ${invoice.invoiceNumber} - VAT`
      ));
    }

    return this.createEntry(companyId, userId, {
      date: invoice.date || new Date(),
      description: `Invoice ${invoice.invoiceNumber} created`,
      sourceType: 'invoice',
      sourceId: invoice._id,
      sourceReference: invoice.invoiceNumber,
      lines,
      isAutoGenerated: true
    });
  }

  /**
   * Invoice paid (cash received)
   * Debit: Cash/Bank
   * Credit: Accounts Receivable
   */
  static async createInvoicePaymentEntry(companyId, userId, payment) {
    const lines = [];

    // Determine cash account
    const cashAccount = payment.paymentMethod === 'bank' 
      ? DEFAULT_ACCOUNTS.cashAtBank 
      : DEFAULT_ACCOUNTS.cashInHand;

    // Debit: Cash/Bank
    lines.push(this.createDebitLine(
      cashAccount,
      payment.amount,
      `Payment for ${payment.invoiceNumber}`
    ));

    // Credit: Accounts Receivable
    lines.push(this.createCreditLine(
      DEFAULT_ACCOUNTS.accountsReceivable,
      payment.amount,
      `Payment for ${payment.invoiceNumber}`
    ));

    return this.createEntry(companyId, userId, {
      date: payment.date || new Date(),
      description: `Payment received for invoice ${payment.invoiceNumber}`,
      sourceType: 'payment',
      sourceReference: payment.invoiceNumber,
      lines,
      isAutoGenerated: true
    });
  }

  /**
   * Credit Note issued
   * Debit: Sales Returns + VAT
   * Credit: Accounts Receivable
   */
  static async createCreditNoteEntry(companyId, userId, creditNote) {
    const lines = [];
    const total = creditNote.total || 0;
    const vatAmount = creditNote.vatAmount || 0;
    const subtotal = total - vatAmount;

    // Debit: Sales Returns
    if (subtotal > 0) {
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.salesReturns,
        subtotal,
        `Credit Note ${creditNote.creditNoteNumber} - Returns`
      ));
    }

    // Debit: VAT Receivable
    if (vatAmount > 0) {
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.vatReceivable,
        vatAmount,
        `Credit Note ${creditNote.creditNoteNumber} - VAT`
      ));
    }

    // Credit: Accounts Receivable
    lines.push(this.createCreditLine(
      DEFAULT_ACCOUNTS.accountsReceivable,
      total,
      `Credit Note ${creditNote.creditNoteNumber}`
    ));

    return this.createEntry(companyId, userId, {
      date: creditNote.date || new Date(),
      description: `Credit Note ${creditNote.creditNoteNumber} issued`,
      sourceType: 'credit_note',
      sourceId: creditNote._id,
      sourceReference: creditNote.creditNoteNumber,
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // PURCHASE TRANSACTIONS
  // =====================================================

  /**
   * Purchase received (on credit)
   * Debit: Inventory + VAT
   * Credit: Accounts Payable
   */
  static async createPurchaseEntry(companyId, userId, purchase) {
    const lines = [];
    const total = purchase.total || 0;
    const vatAmount = purchase.vatAmount || 0;
    const subtotal = total - vatAmount;

    // Debit: Inventory
    if (subtotal > 0) {
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.inventory,
        subtotal,
        `Purchase ${purchase.purchaseNumber} - Inventory`
      ));
    }

    // Debit: VAT Receivable
    if (vatAmount > 0) {
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.vatReceivable,
        vatAmount,
        `Purchase ${purchase.purchaseNumber} - VAT`
      ));
    }

    // Credit: Accounts Payable
    lines.push(this.createCreditLine(
      DEFAULT_ACCOUNTS.accountsPayable,
      total,
      `Purchase ${purchase.purchaseNumber}`
    ));

    return this.createEntry(companyId, userId, {
      date: purchase.date || new Date(),
      description: `Purchase ${purchase.purchaseNumber} received`,
      sourceType: 'purchase',
      sourceId: purchase._id,
      sourceReference: purchase.purchaseNumber,
      lines,
      isAutoGenerated: true
    });
  }

  /**
   * Purchase paid (cash paid)
   * Debit: Accounts Payable
   * Credit: Cash/Bank
   */
  static async createPurchasePaymentEntry(companyId, userId, payment) {
    const lines = [];

    // Determine cash account
    const cashAccount = payment.paymentMethod === 'bank' 
      ? DEFAULT_ACCOUNTS.cashAtBank 
      : DEFAULT_ACCOUNTS.cashInHand;

    // Debit: Accounts Payable
    lines.push(this.createDebitLine(
      DEFAULT_ACCOUNTS.accountsPayable,
      payment.amount,
      `Payment for ${payment.purchaseNumber}`
    ));

    // Credit: Cash/Bank
    lines.push(this.createCreditLine(
      cashAccount,
      payment.amount,
      `Payment for ${payment.purchaseNumber}`
    ));

    return this.createEntry(companyId, userId, {
      date: payment.date || new Date(),
      description: `Payment made for purchase ${payment.purchaseNumber}`,
      sourceType: 'payment',
      sourceReference: payment.purchaseNumber,
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // EXPENSE TRANSACTIONS
  // =====================================================

  /**
   * Expense paid immediately
   * Debit: Expense Account
   * Credit: Cash/Bank
   */
  static async createExpenseEntry(companyId, userId, expense) {
    const lines = [];
    const amount = expense.amount || 0;
    const vatAmount = expense.vatAmount || 0;

    // Determine expense account
    const expenseAccount = expense.category 
      ? DEFAULT_ACCOUNTS[expense.category] || DEFAULT_ACCOUNTS.otherExpenses
      : DEFAULT_ACCOUNTS.otherExpenses;

    // Determine cash account
    const cashAccount = expense.paymentMethod === 'bank' 
      ? DEFAULT_ACCOUNTS.cashAtBank 
      : DEFAULT_ACCOUNTS.cashInHand;

    // Debit: Expense
    lines.push(this.createDebitLine(
      expenseAccount,
      amount,
      expense.description || 'Expense'
    ));

    // Credit: Cash/Bank
    lines.push(this.createCreditLine(
      cashAccount,
      amount,
      expense.description || 'Expense payment'
    ));

    return this.createEntry(companyId, userId, {
      date: expense.date || new Date(),
      description: expense.description || 'Expense payment',
      sourceType: 'expense',
      sourceId: expense._id,
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // ASSET TRANSACTIONS
  // =====================================================

  /**
   * Asset purchased (cash)
   * Debit: Fixed Asset
   * Credit: Cash/Bank
   */
  static async createAssetPurchaseEntry(companyId, userId, asset) {
    const lines = [];

    // Determine asset account based on category
    const assetAccountCode = this.getAssetAccountCode(asset.category);
    const cashAccount = asset.paymentMethod === 'bank' 
      ? DEFAULT_ACCOUNTS.cashAtBank 
      : DEFAULT_ACCOUNTS.cashInHand;

    // Debit: Fixed Asset
    lines.push(this.createDebitLine(
      assetAccountCode,
      asset.purchaseCost,
      `Asset: ${asset.name}`
    ));

    // Credit: Cash/Bank
    lines.push(this.createCreditLine(
      cashAccount,
      asset.purchaseCost,
      `Asset purchase: ${asset.name}`
    ));

    return this.createEntry(companyId, userId, {
      date: asset.purchaseDate || new Date(),
      description: `Asset purchased: ${asset.name}`,
      sourceType: 'asset',
      sourceId: asset._id,
      sourceReference: asset.assetCode,
      lines,
      isAutoGenerated: true
    });
  }

  /**
   * Monthly Depreciation
   * Debit: Depreciation Expense
   * Credit: Accumulated Depreciation
   */
  static async createDepreciationEntry(companyId, userId, depreciation) {
    const lines = [];

    // Debit: Depreciation Expense
    lines.push(this.createDebitLine(
      DEFAULT_ACCOUNTS.depreciation,
      depreciation.amount,
      `Depreciation for ${depreciation.period}`
    ));

    // Credit: Accumulated Depreciation
    lines.push(this.createCreditLine(
      DEFAULT_ACCOUNTS.accumulatedDepreciation,
      depreciation.amount,
      `Depreciation for ${depreciation.period}`
    ));

    return this.createEntry(companyId, userId, {
      date: depreciation.date || new Date(),
      description: `Depreciation expense - ${depreciation.period}`,
      sourceType: 'depreciation',
      lines,
      isAutoGenerated: true
    });
  }

  /**
   * Asset Disposal
   * Entry depends on whether there's gain or loss
   * 
   * If Gain (Proceeds > NBV):
   *   Debit: Cash/Bank (proceeds)
   *   Debit: Accumulated Depreciation (NBV)
   *   Credit: Fixed Asset (cost)
   *   Credit: Gain on Disposal
   * 
   * If Loss (NBV > Proceeds):
   *   Debit: Cash/Bank (proceeds)
   *   Debit: Accumulated Depreciation
   *   Debit: Loss on Disposal
   *   Credit: Fixed Asset (cost)
   */
  static async createAssetDisposalEntry(companyId, userId, asset) {
    const lines = [];

    const cost = asset.purchaseCost || 0;
    const accumulatedDep = asset.accumulatedDepreciation || 0;
    const proceeds = asset.disposalAmount || 0;
    const netBookValue = cost - accumulatedDep;
    const gainLoss = proceeds - netBookValue;

    // Determine cash account
    const cashAccount = asset.paymentMethod === 'bank' 
      ? DEFAULT_ACCOUNTS.cashAtBank 
      : DEFAULT_ACCOUNTS.cashInHand;

    // Determine asset account
    const assetAccountCode = this.getAssetAccountCode(asset.category);

    // Debit: Cash/Bank (proceeds)
    if (proceeds > 0) {
      lines.push(this.createDebitLine(
        cashAccount,
        proceeds,
        `Asset disposal proceeds: ${asset.name}`
      ));
    }

    // Debit: Accumulated Depreciation
    if (accumulatedDep > 0) {
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.accumulatedDepreciation,
        accumulatedDep,
        `Remove accumulated depreciation: ${asset.name}`
      ));
    }

    // Credit: Fixed Asset (original cost)
    lines.push(this.createCreditLine(
      assetAccountCode,
      cost,
      `Remove asset cost: ${asset.name}`
    ));

    // Handle Gain or Loss
    if (gainLoss > 0) {
      // Gain
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.gainOnDisposal,
        gainLoss,
        `Gain on disposal: ${asset.name}`
      ));
    } else if (gainLoss < 0) {
      // Loss
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.lossOnDisposal,
        Math.abs(gainLoss),
        `Loss on disposal: ${asset.name}`
      ));
    }

    return this.createEntry(companyId, userId, {
      date: asset.disposalDate || new Date(),
      description: `Asset disposed: ${asset.name}`,
      sourceType: 'asset',
      sourceId: asset._id,
      sourceReference: asset.assetCode,
      lines,
      isAutoGenerated: true,
      notes: `Disposal - Cost: ${cost}, Accum Dep: ${accumulatedDep}, Proceeds: ${proceeds}, Gain/Loss: ${gainLoss}`
    });
  }

  // =====================================================
  // LOAN TRANSACTIONS
  // =====================================================

  /**
   * Loan received
   * Debit: Cash/Bank
   * Credit: Loan Liability
   */
  static async createLoanReceivedEntry(companyId, userId, loan) {
    const lines = [];

    const cashAccount = loan.paymentMethod === 'bank' 
      ? DEFAULT_ACCOUNTS.cashAtBank 
      : DEFAULT_ACCOUNTS.cashInHand;

    const loanAccount = loan.loanType === 'short_term'
      ? DEFAULT_ACCOUNTS.shortTermLoans
      : DEFAULT_ACCOUNTS.longTermLoans;

    // Debit: Cash/Bank
    lines.push(this.createDebitLine(
      cashAccount,
      loan.principalAmount,
      `Loan received: ${loan.loanNumber}`
    ));

    // Credit: Loan Liability
    lines.push(this.createCreditLine(
      loanAccount,
      loan.principalAmount,
      `Loan: ${loan.loanNumber}`
    ));

    return this.createEntry(companyId, userId, {
      date: loan.disbursementDate || new Date(),
      description: `Loan received: ${loan.loanNumber}`,
      sourceType: 'loan',
      sourceId: loan._id,
      sourceReference: loan.loanNumber,
      lines,
      isAutoGenerated: true
    });
  }

  /**
   * Loan payment (principal + interest)
   * Debit: Loan Liability (principal)
   * Debit: Interest Expense
   * Credit: Cash/Bank
   */
  static async createLoanPaymentEntry(companyId, userId, payment) {
    const lines = [];

    const cashAccount = payment.paymentMethod === 'bank' 
      ? DEFAULT_ACCOUNTS.cashAtBank 
      : DEFAULT_ACCOUNTS.cashInHand;

    const principal = payment.principalAmount || 0;
    const interest = payment.interestAmount || 0;
    const total = principal + interest;

    // Debit: Loan Liability (principal)
    if (principal > 0) {
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.shortTermLoans,
        principal,
        `Loan payment: ${payment.loanNumber}`
      ));
    }

    // Debit: Interest Expense
    if (interest > 0) {
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.interestExpense,
        interest,
        `Interest payment: ${payment.loanNumber}`
      ));
    }

    // Credit: Cash/Bank
    lines.push(this.createCreditLine(
      cashAccount,
      total,
      `Loan payment: ${payment.loanNumber}`
    ));

    return this.createEntry(companyId, userId, {
      date: payment.date || new Date(),
      description: `Loan payment: ${payment.loanNumber}`,
      sourceType: 'loan',
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // HELPER METHODS
  // =====================================================

  /**
   * Get asset account code based on category
   */
  static getAssetAccountCode(category) {
    const categoryMap = {
      'equipment': DEFAULT_ACCOUNTS.equipment,
      'computers': DEFAULT_ACCOUNTS.computers,
      'vehicles': DEFAULT_ACCOUNTS.vehicles,
      'furniture': DEFAULT_ACCOUNTS.furniture,
      'buildings': DEFAULT_ACCOUNTS.buildings,
      'land': DEFAULT_ACCOUNTS.land,
      'machinery': DEFAULT_ACCOUNTS.machinery,
      'other': '1790'
    };
    return categoryMap[category] || DEFAULT_ACCOUNTS.equipment;
  }

  /**
   * Create manual journal entry
   */
  static async createManualEntry(companyId, userId, entryData) {
    return this.createEntry(companyId, userId, {
      ...entryData,
      sourceType: 'manual',
      isAutoGenerated: false
    });
  }

  // =====================================================
  // BANK TRANSFER
  // =====================================================

  /**
   * Bank transfer between accounts
   * Debit: Destination Bank Account
   * Credit: Source Bank Account
   */
  static async createBankTransferEntry(companyId, userId, options) {
    const {
      fromAccountCode,
      toAccountCode,
      fromAccountName,
      toAccountName,
      amount,
      description,
      referenceNumber,
      date = new Date()
    } = options;

    const lines = [];

    // Debit: Destination Bank Account (receiving money)
    lines.push(this.createDebitLine(
      toAccountCode || DEFAULT_ACCOUNTS.cashAtBank,
      amount,
      `Transfer to ${toAccountName || 'Bank Account'}`
    ));

    // Credit: Source Bank Account (sending money)
    lines.push(this.createCreditLine(
      fromAccountCode || DEFAULT_ACCOUNTS.cashAtBank,
      amount,
      `Transfer from ${fromAccountName || 'Bank Account'}`
    ));

    return this.createEntry(companyId, userId, {
      date,
      description: description || `Bank transfer`,
      sourceType: 'bank_transfer',
      sourceReference: referenceNumber,
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // PURCHASE RETURN
  // =====================================================

  /**
   * Purchase return (returning goods to supplier)
   * Debit: Accounts Payable
   * Credit: Inventory + VAT Receivable
   */
  static async createPurchaseReturnEntry(companyId, userId, purchaseReturn) {
    const lines = [];
    const total = purchaseReturn.total || 0;
    const vatAmount = purchaseReturn.vatAmount || 0;
    const subtotal = total - vatAmount;

    // Debit: Accounts Payable
    lines.push(this.createDebitLine(
      DEFAULT_ACCOUNTS.accountsPayable,
      total,
      `Purchase Return ${purchaseReturn.returnNumber}`
    ));

    // Credit: Inventory
    if (subtotal > 0) {
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.inventory,
        subtotal,
        `Purchase Return ${purchaseReturn.returnNumber} - Inventory`
      ));
    }

    // Credit: VAT Receivable
    if (vatAmount > 0) {
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.vatReceivable,
        vatAmount,
        `Purchase Return ${purchaseReturn.returnNumber} - VAT`
      ));
    }

    return this.createEntry(companyId, userId, {
      date: purchaseReturn.date || new Date(),
      description: `Purchase Return ${purchaseReturn.returnNumber} approved`,
      sourceType: 'purchase_return',
      sourceId: purchaseReturn._id,
      sourceReference: purchaseReturn.returnNumber,
      lines,
      isAutoGenerated: true
    });
  }

  /**
   * Purchase return refund
   * Debit: Accounts Payable
   * Credit: Cash/Bank
   */
  static async createPurchaseReturnRefundEntry(companyId, userId, refund) {
    const lines = [];

    // Determine cash account
    const cashAccount = refund.paymentMethod === 'bank'
      ? DEFAULT_ACCOUNTS.cashAtBank
      : DEFAULT_ACCOUNTS.cashInHand;

    // Debit: Accounts Payable
    lines.push(this.createDebitLine(
      DEFAULT_ACCOUNTS.accountsPayable,
      refund.amount,
      `Refund for ${refund.returnNumber}`
    ));

    // Credit: Cash/Bank
    lines.push(this.createCreditLine(
      cashAccount,
      refund.amount,
      `Refund for ${refund.returnNumber}`
    ));

    return this.createEntry(companyId, userId, {
      date: refund.date || new Date(),
      description: `Purchase Return ${refund.returnNumber} refund`,
      sourceType: 'purchase_return',
      sourceReference: refund.returnNumber,
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // STOCK ADJUSTMENT
  // =====================================================

  /**
   * Stock adjustment (increase)
   * Debit: Inventory
   * Credit: Stock Adjustment (Revenue) / Cost of Goods Sold
   */
  static async createStockAdjustmentEntry(companyId, userId, adjustment) {
    const lines = [];
    const amount = adjustment.adjustmentAmount || 0;
    const adjustmentType = adjustment.adjustmentType; // 'increase' or 'decrease'

    if (adjustmentType === 'increase') {
      // Debit: Inventory
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.inventory,
        amount,
        `Stock adjustment increase: ${adjustment.productName}`
      ));

      // Credit: Stock Adjustment Income
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.stockAdjustment || '4100',
        amount,
        `Stock adjustment increase: ${adjustment.productName}`
      ));
    } else {
      // Debit: Cost of Goods Sold
      lines.push(this.createDebitLine(
        DEFAULT_ACCOUNTS.costOfGoodsSold,
        amount,
        `Stock adjustment decrease: ${adjustment.productName}`
      ));

      // Credit: Inventory
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.inventory,
        amount,
        `Stock adjustment decrease: ${adjustment.productName}`
      ));
    }

    return this.createEntry(companyId, userId, {
      date: adjustment.date || new Date(),
      description: `Stock adjustment: ${adjustment.productName} - ${adjustmentType}`,
      sourceType: 'stock_adjustment',
      sourceId: adjustment._id,
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // PAYROLL
  // =====================================================

  /**
   * Payroll payment
   * Debit: Payroll Expense
   * Credit: Cash/Bank (net pay)
   * Credit: Tax Payable (withheld tax)
   * Credit: Employee Deductions Payable
   */
  static async createPayrollEntry(companyId, userId, payroll) {
    const lines = [];

    const grossPay = payroll.grossPay || 0;
    const netPay = payroll.netPay || 0;
    const taxWithheld = payroll.taxWithheld || 0;
    const ssnWithheld = payroll.ssnWithheld || 0;
    const otherDeductions = payroll.otherDeductions || 0;

    // Determine cash account
    const cashAccount = payroll.paymentMethod === 'bank'
      ? DEFAULT_ACCOUNTS.cashAtBank
      : DEFAULT_ACCOUNTS.cashInHand;

    // Debit: Payroll Expense
    lines.push(this.createDebitLine(
      DEFAULT_ACCOUNTS.payrollExpenses || '5410',
      grossPay,
      `Payroll: ${payroll.period || 'Salary'}`
    ));

    // Credit: Cash/Bank (net pay to employee)
    if (netPay > 0) {
      lines.push(this.createCreditLine(
        cashAccount,
        netPay,
        `Net salary payment: ${payroll.period || 'Salary'}`
      ));
    }

    // Credit: Tax Payable (withheld tax)
    if (taxWithheld > 0) {
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.taxPayable || '2310',
        taxWithheld,
        `Tax withheld: ${payroll.period || 'Salary'}`
      ));
    }

    // Credit: RSSB Payable (social security)
    if (ssnWithheld > 0) {
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.rssbPayable || '2320',
        ssnWithheld,
        `RSSB contribution: ${payroll.period || 'Salary'}`
      ));
    }

    // Credit: Employer Contribution Payable
    const employerContribution = payroll.employerContribution || 0;
    if (employerContribution > 0) {
      lines.push(this.createCreditLine(
        DEFAULT_ACCOUNTS.employerContributionPayable || '2310',
        employerContribution,
        `Employer contribution: ${payroll.period || 'Salary'}`
      ));
    }

    return this.createEntry(companyId, userId, {
      date: payroll.paymentDate || new Date(),
      description: `Payroll: ${payroll.period || 'Salary'} - ${payroll.employeeName}`,
      sourceType: 'payroll',
      sourceId: payroll._id,
      lines,
      isAutoGenerated: true
    });
  }

  // =====================================================
  // TAX PAYMENT
  // =====================================================

  /**
   * Tax payment
   * Debit: Tax Payable
   * Credit: Cash/Bank
   */
  static async createTaxPaymentEntry(companyId, userId, taxPayment) {
    const lines = [];
    const amount = taxPayment.amount || 0;

    // Determine cash account
    const cashAccount = taxPayment.paymentMethod === 'bank'
      ? DEFAULT_ACCOUNTS.cashAtBank
      : DEFAULT_ACCOUNTS.cashInHand;

    // Debit: Tax Payable
    lines.push(this.createDebitLine(
      DEFAULT_ACCOUNTS.taxPayable || '2310',
      amount,
      `Tax payment: ${taxPayment.taxType || 'VAT'}`
    ));

    // Credit: Cash/Bank
    lines.push(this.createCreditLine(
      cashAccount,
      amount,
      `Tax payment: ${taxPayment.taxType || 'VAT'}`
    ));

    return this.createEntry(companyId, userId, {
      date: taxPayment.paymentDate || new Date(),
      description: `Tax payment: ${taxPayment.taxType || 'VAT'}`,
      sourceType: 'tax_payment',
      sourceId: taxPayment._id,
      lines,
      isAutoGenerated: true
    });
  }
}

module.exports = JournalService;
