const mongoose = require('mongoose');
require('dotenv').config();
const argv = require('minimist')(process.argv.slice(2));

async function run() {
  await mongoose.connect(process.env.MONGODB_URI, { useNewUrlParser: true, useUnifiedTopology: true });
  const JournalEntry = require('../models/JournalEntry');
  const Company = require('../models/Company');
  const User = require('../models/User');
  const { DEFAULT_ACCOUNTS, getAccount } = require('../constants/chartOfAccounts');

  const apply = !!argv.apply;

  console.log(`Share capital entries script (apply=${apply})`);
  console.log('=======================================');

  const companies = await Company.find({});
  for (const company of companies) {
    const sc = (company.equity && company.equity.shareCapital) || 0;
    if (!sc || sc <= 0) {
      console.log(`${company.name}: no share capital to process (${sc})`);
      continue;
    }

    const existing = await JournalEntry.find({ company: company._id, status: 'posted', 'lines.accountCode': '3000' });
    if (existing && existing.length > 0) {
      console.log(`${company.name}: already has ${existing.length} posted entries for account 3000; skipping`);
      continue;
    }

    // Find a user for createdBy/postedBy
    let user = await User.findOne({ company: company._id }).lean();
    if (!user) {
      user = await User.findOne({ role: 'platform_admin' }).lean();
    }
    const userId = user ? user._id : null;

    const cashAccountCode = DEFAULT_ACCOUNTS.cashAtBank || DEFAULT_ACCOUNTS.cashInHand || '1100';
    const cashAccount = getAccount(cashAccountCode) || { name: 'Cash' };
    const shareAccount = getAccount('3000') || { name: 'Share Capital' };

    const lines = [
      {
        accountCode: cashAccountCode,
        accountName: cashAccount.name,
        description: 'Initial share capital - debit',
        debit: sc,
        credit: 0,
        reference: 'initial_share_capital'
      },
      {
        accountCode: '3000',
        accountName: shareAccount.name,
        description: 'Initial share capital - credit',
        debit: 0,
        credit: sc,
        reference: 'initial_share_capital'
      }
    ];

    if (!apply) {
      console.log(`${company.name}: would create posted JournalEntry for ${sc} (debit ${cashAccountCode}, credit 3000) createdBy=${userId}`);
    } else {
      // Try to create entry, retrying if entryNumber collides
      let entry = null;
      let attempts = 0;
      const maxAttempts = 6;
      while (!entry && attempts < maxAttempts) {
        attempts++;
        let entryNumber = await JournalEntry.generateEntryNumber(company._id);
        try {
          entry = await JournalEntry.create({
            company: company._id,
            entryNumber,
            date: new Date(),
            description: 'Initial share capital import',
            lines: lines.map(l => ({
              accountCode: l.accountCode,
              accountName: l.accountName,
              description: l.description,
              debit: l.debit,
              credit: l.credit,
              reference: l.reference
            })),
            totalDebit: sc,
            totalCredit: sc,
            status: 'posted',
            sourceType: 'manual',
            sourceReference: 'initial_share_capital_import',
            isAutoGenerated: true,
            createdBy: userId,
            postedBy: userId
          });
        } catch (err) {
          // Duplicate entryNumber error, try a company-suffixed entryNumber then retry
          if (err && err.code === 11000 && err.keyPattern && err.keyPattern.entryNumber) {
            // Create a fallback entryNumber with company suffix and attempt once
            const suffix = company._id.toString().slice(-6);
            entryNumber = `${entryNumber}-${suffix}-${String(attempts).padStart(2, '0')}`;
            try {
              entry = await JournalEntry.create({
                company: company._id,
                entryNumber,
                date: new Date(),
                description: 'Initial share capital import',
                lines: lines.map(l => ({
                  accountCode: l.accountCode,
                  accountName: l.accountName,
                  description: l.description,
                  debit: l.debit,
                  credit: l.credit,
                  reference: l.reference
                })),
                totalDebit: sc,
                totalCredit: sc,
                status: 'posted',
                sourceType: 'manual',
                sourceReference: 'initial_share_capital_import',
                isAutoGenerated: true,
                createdBy: userId,
                postedBy: userId
              });
            } catch (err2) {
              // if still duplicate or other error, wait and retry generateEntryNumber
              await new Promise(r => setTimeout(r, 200));
              continue;
            }
            continue;
          }
          throw err;
        }
      }

      if (!entry) {
        console.error(`${company.name}: failed to create JournalEntry after ${maxAttempts} attempts`);
      } else {
        console.log(`${company.name}: created JournalEntry ${entry.entryNumber} for ${sc}`);
      }
    }
  }

  await mongoose.disconnect();
}

run().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
