/**
 * Migration Script: Fix Credit Note VAT and AR Entries
 * 
 * This script corrects journal entries for credit notes:
 * 1. Changes VAT Receivable (1500) to VAT Payable (2100)
 * 2. Changes Accounts Receivable (1300) to Cash at Bank (1100)
 * 
 * Original (WRONG):
 *   DR 4100 Sales Returns
 *   DR 1500 VAT Receivable (should be 2100)
 *   CR 1300 Accounts Receivable (should be 1100)
 * 
 * Corrected:
 *   DR 4100 Sales Returns
 *   DR 2100 VAT Payable
 *   CR 1100 Cash at Bank
 * 
 * Run with: node scripts/fixCreditNoteVatEntries.js
 */

const mongoose = require('mongoose');
const dotenv = require('dotenv');

// Load environment
dotenv.config({ path: require('path').resolve(__dirname, '../.env') });

const JournalEntry = require('../models/JournalEntry');
const { DEFAULT_ACCOUNTS } = require('../constants/chartOfAccounts');

// Connect to MongoDB
const connectDB = async () => {
  try {
    const conn = await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/stockmanagement');
    console.log(`MongoDB Connected: ${conn.connection.host}`);
    return conn;
  } catch (error) {
    console.error('Database connection failed:', error.message);
    process.exit(1);
  }
};

async function fixCreditNoteVatEntries() {
  console.log('=== Starting Credit Note VAT + AR Fix ===\n');
  
  const vatReceivableCode = DEFAULT_ACCOUNTS.vatReceivable;
  const vatPayableCode = DEFAULT_ACCOUNTS.vatPayable;
  const arCode = DEFAULT_ACCOUNTS.accountsReceivable;
  const cashCode = DEFAULT_ACCOUNTS.cashAtBank;
  
  try {
    // Find all credit note journal entries that are not voided
    const creditNoteEntries = await JournalEntry.find({
      sourceType: 'credit_note',
      status: { $ne: 'voided' }
    }).sort({ createdAt: -1 });

    console.log(`Found ${creditNoteEntries.length} credit note journal entries`);

    let fixedCount = 0;
    let skippedCount = 0;

    for (const entry of creditNoteEntries) {
      console.log(`\nProcessing: ${entry.entryNumber}`);
      
      const hasVatReceivable = entry.lines.some(line => 
        line.accountCode === vatReceivableCode && line.debit > 0
      );
      
      const hasAr = entry.lines.some(line => 
        line.accountCode === arCode && line.credit > 0
      );
      
      const hasVatPayable = entry.lines.some(line => 
        line.accountCode === vatPayableCode && line.debit > 0
      );

      // Check if needs fixing (has VAT Receivable OR has AR)
      const needsVatFix = hasVatReceivable && !hasVatPayable;
      const needsArFix = hasAr;
      
      if (needsVatFix || needsArFix) {
        console.log(`  ❌ Needs fixing - VAT: ${needsVatFix ? 'YES' : 'No'}, AR: ${needsArFix ? 'YES' : 'No'}`);
        
        // Void the old entry
        entry.status = 'voided';
        entry.notes = entry.notes || '';
        entry.notes += `\n[VOIDED - Migration: Fixed VAT Receivable→VAT Payable and AR→Cash at Bank on ${new Date().toISOString()}]`;
        await entry.save();
        
        // Create corrected entry
        const newLines = entry.lines.map(line => {
          // Fix VAT Receivable → VAT Payable (debit side)
          if (line.accountCode === vatReceivableCode && line.debit > 0) {
            return {
              ...line,
              accountCode: vatPayableCode,
              accountName: 'VAT Payable',
              description: (line.description || '').replace('VAT Receivable', 'VAT Payable')
            };
          }
          // Fix AR → Cash at Bank (credit side)
          if (line.accountCode === arCode && line.credit > 0) {
            return {
              ...line,
              accountCode: cashCode,
              accountName: 'Cash at Bank',
              description: (line.description || '').replace('Accounts Receivable', 'Cash at Bank')
            };
          }
          return line;
        });
        
        // Create the corrected journal entry
        const correctedEntry = await JournalEntry.create({
          company: entry.company,
          entryNumber: await JournalEntry.generateEntryNumber(entry.company),
          date: entry.date,
          description: entry.description + ' [CORRECTED - VAT & AR]',
          sourceType: entry.sourceType,
          sourceId: entry.sourceId,
          sourceReference: entry.sourceReference,
          lines: newLines,
          totalDebit: entry.totalDebit,
          totalCredit: entry.totalCredit,
          isAutoGenerated: entry.isAutoGenerated,
          createdBy: entry.createdBy,
          postedBy: entry.postedBy,
          status: 'posted',
          notes: `Corrected: VAT Receivable→VAT Payable, Accounts Receivable→Cash at Bank. Original: ${entry.entryNumber}`
        });
        
        console.log(`  ✅ Fixed! New entry: ${correctedEntry.entryNumber}`);
        fixedCount++;
      } else {
        console.log(`  ✅ Already correct`);
        skippedCount++;
      }
    }

    console.log('\n=== Summary ===');
    console.log(`Total entries processed: ${creditNoteEntries.length}`);
    console.log(`Fixed: ${fixedCount}`);
    console.log(`Skipped (already correct): ${skippedCount}`);
    console.log('\n=== Migration Complete ===');

  } catch (error) {
    console.error('Error during migration:', error);
  } finally {
    await mongoose.disconnect();
    console.log('Disconnected from MongoDB');
    process.exit(0);
  }
}

// Run if called directly
if (require.main === module) {
  connectDB().then(() => {
    fixCreditNoteVatEntries();
  });
}

module.exports = fixCreditNoteVatEntries;
