/**
 * Migration Script: Create Journal Entries for Existing Paid Expenses
 * 
 * This script finds all expenses marked as 'paid' that don't have corresponding
 * journal entries and creates them.
 * 
 * Run with: node scripts/fixExpenseJournalEntries.js
 */

const mongoose = require('mongoose');
const dotenv = require('dotenv');

// Load environment
dotenv.config({ path: require('path').resolve(__dirname, '../.env') });

const Expense = require('../models/Expense');
const JournalEntry = require('../models/JournalEntry');
const JournalService = require('../services/journalService');
const { DEFAULT_ACCOUNTS } = require('../constants/chartOfAccounts');

// Connect to MongoDB
const connectDB = async () => {
  try {
    const conn = await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/stockmanagement');
    console.log(`MongoDB Connected: ${conn.connection.host}`);
    return conn;
  } catch (error) {
    console.error('Database connection failed:', error.message);
    process.exit(1);
  }
};

async function createExpenseJournalEntries() {
  console.log('=== Creating Journal Entries for Existing Paid Expenses ===\n');
  
  try {
    // Find all paid expenses
    const paidExpenses = await Expense.find({ 
      paid: true,
      status: { $ne: 'cancelled' }
    }).populate('createdBy', 'name');

    console.log(`Found ${paidExpenses.length} paid expenses`);

    let createdCount = 0;
    let skippedCount = 0;

    for (const expense of paidExpenses) {
      // Check if there's already a journal entry for this expense
      const existingEntry = await JournalEntry.findOne({
        sourceType: 'expense',
        sourceId: expense._id
      });

      if (existingEntry) {
        console.log(`\nSkipping ${expense._id} - already has journal entry ${existingEntry.entryNumber}`);
        skippedCount++;
        continue;
      }

      try {
        // Determine cash account based on payment method
        let cashAccount;
        if (expense.paymentMethod === 'bank_transfer' || expense.paymentMethod === 'cheque') {
          cashAccount = DEFAULT_ACCOUNTS.cashAtBank;
        } else if (expense.paymentMethod === 'mobile_money') {
          cashAccount = DEFAULT_ACCOUNTS.mtnMoMo;
        } else {
          cashAccount = DEFAULT_ACCOUNTS.cashInHand;
        }

        // Determine expense account based on type
        // Map expense type to account code
        let expenseAccount;
        const type = expense.type;
        
        if (type) {
          // Map underscore format to camelCase for DEFAULT_ACCOUNTS lookup
          const typeMap = {
            'salaries_wages': 'salariesWages',
            'transport_delivery': 'transport',
            'marketing_advertising': 'marketing',
            'interest_income': 'interestIncome',
            'other_income': 'otherIncome',
            'other_expense': 'otherExpenses'
          };
          
          const mappedType = typeMap[type] || type;
          expenseAccount = DEFAULT_ACCOUNTS[mappedType] || DEFAULT_ACCOUNTS.otherExpenses;
        } else {
          expenseAccount = DEFAULT_ACCOUNTS.otherExpenses;
        }

        // Create journal entry
        const entry = await JournalEntry.create({
          company: expense.company,
          entryNumber: await JournalEntry.generateEntryNumber(expense.company),
          date: expense.expenseDate || expense.createdAt,
          description: expense.description || expense.type || 'Expense',
          sourceType: 'expense',
          sourceId: expense._id,
          sourceReference: expense.reference || null,
          lines: [
            {
              accountCode: expenseAccount,
              accountName: expense.type || 'Other Expenses',
              description: expense.description || 'Expense',
              debit: expense.amount || 0,
              credit: 0
            },
            {
              accountCode: cashAccount,
              accountName: cashAccount === DEFAULT_ACCOUNTS.cashAtBank ? 'Cash at Bank' : 
                          cashAccount === DEFAULT_ACCOUNTS.mtnMoMo ? 'MTN MoMo' : 'Cash in Hand',
              description: 'Expense payment',
              debit: 0,
              credit: expense.amount || 0
            }
          ],
          totalDebit: expense.amount || 0,
          totalCredit: expense.amount || 0,
          isAutoGenerated: true,
          createdBy: expense.createdBy._id,
          postedBy: expense.createdBy._id,
          status: 'posted',
          notes: 'Created by migration script - expense was marked as paid but had no journal entry'
        });

        console.log(`\n✅ Created journal entry ${entry.entryNumber} for expense ${expense._id}`);
        console.log(`   DR ${expenseAccount} ${expense.amount}`);
        console.log(`   CR ${cashAccount} ${expense.amount}`);
        createdCount++;

      } catch (createError) {
        console.error(`\n❌ Error creating journal entry for expense ${expense._id}:`, createError.message);
      }
    }

    console.log('\n=== Summary ===');
    console.log(`Total paid expenses: ${paidExpenses.length}`);
    console.log(`Journal entries created: ${createdCount}`);
    console.log(`Skipped (already have entries): ${skippedCount}`);
    console.log('\n=== Migration Complete ===');

  } catch (error) {
    console.error('Error during migration:', error);
  } finally {
    await mongoose.disconnect();
    console.log('Disconnected from MongoDB');
    process.exit(0);
  }
}

// Run if called directly
if (require.main === module) {
  connectDB().then(() => {
    createExpenseJournalEntries();
  });
}

module.exports = createExpenseJournalEntries;
