/**
 * Migration Script: Fix Expense Entries to Use Cash at Bank
 * 
 * This script corrects journal entries for expenses that were NOT using Cash at Bank (1100)
 * All expenses should be deducted from Cash at Bank
 * 
 * Run with: node scripts/fixExpenseCashEntries.js
 */

const mongoose = require('mongoose');
const dotenv = require('dotenv');

// Load environment
dotenv.config({ path: require('path').resolve(__dirname, '../.env') });

const JournalEntry = require('../models/JournalEntry');
const { DEFAULT_ACCOUNTS } = require('../constants/chartOfAccounts');

// Connect to MongoDB
const connectDB = async () => {
  try {
    const conn = await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/stockmanagement');
    console.log(`MongoDB Connected: ${conn.connection.host}`);
    return conn;
  } catch (error) {
    console.error('Database connection failed:', error.message);
    process.exit(1);
  }
};

async function fixExpenseCashEntries() {
  console.log('=== Starting Expense Cash at Bank Fix ===\n');
  
  const cashAtBankCode = DEFAULT_ACCOUNTS.cashAtBank;
  const cashInHandCode = DEFAULT_ACCOUNTS.cashInHand;
  const mtnMoMoCode = DEFAULT_ACCOUNTS.mtnMoMo;
  
  try {
    // Find all expense journal entries that are not voided
    const expenseEntries = await JournalEntry.find({
      sourceType: 'expense',
      status: { $ne: 'voided' }
    }).sort({ createdAt: -1 });

    console.log(`Found ${expenseEntries.length} expense journal entries`);

    let fixedCount = 0;
    let skippedCount = 0;

    for (const entry of expenseEntries) {
      // Check if any credit line uses wrong cash account
      const hasWrongCash = entry.lines.some(line => 
        (line.accountCode === cashInHandCode || line.accountCode === mtnMoMoCode) && 
        line.credit > 0
      );
      
      const hasCashAtBank = entry.lines.some(line => 
        line.accountCode === cashAtBankCode && line.credit > 0
      );

      if (hasWrongCash && !hasCashAtBank) {
        console.log(`\nProcessing: ${entry.entryNumber}`);
        console.log(`  ❌ Has wrong cash account - needs fixing`);
        
        // Void the old entry
        entry.status = 'voided';
        entry.notes = entry.notes || '';
        entry.notes += `\n[VOIDED - Migration: Changed to Cash at Bank on ${new Date().toISOString()}]`;
        await entry.save();
        
        // Create corrected entry - replace wrong cash with Cash at Bank
        const newLines = entry.lines.map(line => {
          // Change Cash in Hand or MTN MoMo to Cash at Bank (credit side)
          if ((line.accountCode === cashInHandCode || line.accountCode === mtnMoMoCode) && line.credit > 0) {
            return {
              ...line,
              accountCode: cashAtBankCode,
              accountName: 'Cash at Bank',
              description: (line.description || '').replace('Cash in Hand', 'Cash at Bank').replace('MTN MoMo', 'Cash at Bank')
            };
          }
          return line;
        });
        
        // Create the corrected journal entry
        const correctedEntry = await JournalEntry.create({
          company: entry.company,
          entryNumber: await JournalEntry.generateEntryNumber(entry.company),
          date: entry.date,
          description: entry.description + ' [CORRECTED - Cash at Bank]',
          sourceType: entry.sourceType,
          sourceId: entry.sourceId,
          sourceReference: entry.sourceReference,
          lines: newLines,
          totalDebit: entry.totalDebit,
          totalCredit: entry.totalCredit,
          isAutoGenerated: entry.isAutoGenerated,
          createdBy: entry.createdBy,
          postedBy: entry.postedBy,
          status: 'posted',
          notes: `Corrected: Changed to Cash at Bank (1100). Original: ${entry.entryNumber}`
        });
        
        console.log(`  ✅ Fixed! New entry: ${correctedEntry.entryNumber}`);
        fixedCount++;
      } else {
        skippedCount++;
      }
    }

    console.log('\n=== Summary ===');
    console.log(`Total entries processed: ${expenseEntries.length}`);
    console.log(`Fixed: ${fixedCount}`);
    console.log(`Skipped (already correct): ${skippedCount}`);
    console.log('\n=== Migration Complete ===');

  } catch (error) {
    console.error('Error during migration:', error);
  } finally {
    await mongoose.disconnect();
    console.log('Disconnected from MongoDB');
    process.exit(0);
  }
}

// Run if called directly
if (require.main === module) {
  connectDB().then(() => {
    fixExpenseCashEntries();
  });
}

module.exports = fixExpenseCashEntries;
