const mongoose = require('mongoose');
const dotenv = require('dotenv');

dotenv.config({ path: __dirname + '/../.env' });

const JournalEntry = require('../models/JournalEntry');
const Loan = require('../models/Loan');
const JournalService = require('../services/journalService');
const { DEFAULT_ACCOUNTS } = require('../constants/chartOfAccounts');

async function fixLoanPayments() {
  await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/stock-management');
  console.log('MongoDB connected');

  // Find all loan payments (entries with "Loan payment" in description)
  const entries = await JournalEntry.find({
    description: { $regex: /Loan payment/i }
  }).sort({ date: -1 });

  console.log(`Found ${entries.length} loan payment journal entries`);

  // Get all loans to map loan numbers to loan types
  const loans = await Loan.find({});
  const loanMap = {};
  loans.forEach(loan => {
    loanMap[loan.loanNumber] = loan;
  });

  let fixedCount = 0;
  let errorCount = 0;

  for (const entry of entries) {
    try {
      // Extract loan number from description (e.g., "Loan payment: LN-00001")
      const match = entry.description.match(/Loan payment: (.+)/);
      if (!match) continue;
      
      const loanNumber = match[1].trim();
      const loan = loanMap[loanNumber];
      
      if (!loan) {
        console.log(`Loan not found for: ${loanNumber}`);
        continue;
      }

      // Calculate correct interest and principal based on the loan's interest rate
      const totalPayment = entry.totalDebit;
      let interestAmount = 0;
      
      if (loan.interestRate > 0) {
        const monthlyInterestRate = loan.interestRate / 100 / 12;
        interestAmount = Math.round(loan.originalAmount * monthlyInterestRate);
      }
      
      const principalAmount = totalPayment - interestAmount;
      const loanAccount = loan.loanType === 'long-term' 
        ? DEFAULT_ACCOUNTS.longTermLoans 
        : DEFAULT_ACCOUNTS.shortTermLoans;

      console.log(`\nLoan: ${loanNumber} (${loan.loanType})`);
      console.log(`  Total payment: ${totalPayment}`);
      console.log(`  Interest (calculated): ${interestAmount}`);
      console.log(`  Principal (calculated): ${principalAmount}`);
      console.log(`  Current entry lines:`);
      
      entry.lines.forEach(line => {
        console.log(`    ${line.accountCode} ${line.accountName}: DR ${line.debit}, CR ${line.credit}`);
      });

      // Check if this needs fixing (wrong account or missing interest)
      const needsFix = entry.lines.some(line => 
        (line.accountCode === '2700' && loan.loanType === 'long-term') ||
        (line.accountCode === '2900' && loan.loanType === 'short-term') ||
        entry.lines.length < 3
      );

      if (needsFix) {
        // Delete this entry and create a new correct one
        await JournalEntry.deleteOne({ _id: entry._id });
        
        // Create corrected journal entry
        const lines = [];
        
        // DR Loan Account
        if (principalAmount > 0) {
          lines.push({
            accountCode: loanAccount,
            accountName: loan.loanType === 'long-term' ? 'Long Term Loans' : 'Short Term Loans',
            description: `Loan payment: ${loanNumber}`,
            debit: principalAmount,
            credit: 0,
            reference: ''
          });
        }
        
        // DR Interest Expense
        if (interestAmount > 0) {
          lines.push({
            accountCode: DEFAULT_ACCOUNTS.interestExpense,
            accountName: 'Interest Expense',
            description: `Interest payment: ${loanNumber}`,
            debit: interestAmount,
            credit: 0,
            reference: ''
          });
        }
        
        // CR Cash (use Cash at Bank as default)
        lines.push({
          accountCode: DEFAULT_ACCOUNTS.cashAtBank,
          accountName: 'Cash at Bank',
          description: `Loan payment: ${loanNumber}`,
          debit: 0,
          credit: totalPayment,
          reference: ''
        });

        // Create new entry
        const newEntry = await JournalEntry.create({
          company: entry.company,
          entryNumber: await JournalEntry.generateEntryNumber(entry.company),
          date: entry.date,
          description: entry.description,
          lines: lines,
          totalDebit: totalPayment,
          totalCredit: totalPayment,
          status: 'posted',
          sourceType: 'loan',
          sourceReference: loanNumber,
          isAutoGenerated: true,
          createdBy: entry.createdBy,
          postedBy: entry.postedBy
        });

        console.log(`  ✅ Fixed! New entry: ${newEntry.entryNumber}`);
        console.log(`  New lines:`);
        newEntry.lines.forEach(line => {
          console.log(`    ${line.accountCode} ${line.accountName}: DR ${line.debit}, CR ${line.credit}`);
        });
        
        fixedCount++;
      } else {
        console.log(`  ✅ Already correct`);
      }

    } catch (err) {
      console.log(`  ❌ Error: ${err.message}`);
      errorCount++;
    }
  }

  console.log(`\n=== Summary ===`);
  console.log(`Fixed: ${fixedCount}`);
  console.log(`Errors: ${errorCount}`);

  process.exit(0);
}

fixLoanPayments().catch(e => {
  console.error(e);
  process.exit(1);
});
