const mongoose = require('mongoose');

// Journal Entry Line Schema (individual debit/credit lines)
const journalLineSchema = new mongoose.Schema({
  accountCode: {
    type: String,
    required: true,
    trim: true
  },
  accountName: {
    type: String,
    required: true,
    trim: true
  },
  description: {
    type: String,
    trim: true
  },
  debit: {
    type: Number,
    default: 0,
    min: 0
  },
  credit: {
    type: Number,
    default: 0,
    min: 0
  },
  reference: {
    type: String,
    trim: true
  }
}, { _id: false });

// Journal Entry Main Schema
const journalEntrySchema = new mongoose.Schema({
  // Company reference
  company: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Company',
    required: true
  },
  
  // Entry details
  entryNumber: {
    type: String,
    required: true,
    unique: true
  },
  date: {
    type: Date,
    required: true,
    default: Date.now
  },
  description: {
    type: String,
    required: true,
    trim: true
  },
  
  // Reference to source document (optional)
  sourceType: {
    type: String,
    enum: ['manual', 'invoice', 'purchase', 'credit_note', 'expense', 'asset', 'depreciation', 'loan', 'payment', 'adjustment', 'petty_cash', 'petty_cash_expense', 'petty_cash_replenishment', 'purchase_return', 'stock_adjustment', 'payroll', 'tax_payment', 'bank_transfer', 'opening_balance', 'capital_investment', 'capital_payment', null],
    default: 'manual'
  },
  sourceId: {
    type: mongoose.Schema.Types.ObjectId,
    refPath: 'sourceType'
  },
  sourceReference: {
    type: String,
    trim: true
  },
  
  // Entry lines (debits and credits)
  lines: [journalLineSchema],
  
  // Status
  status: {
    type: String,
    enum: ['draft', 'posted', 'voided'],
    default: 'posted'
  },
  
  // Totals (for validation)
  totalDebit: {
    type: Number,
    default: 0
  },
  totalCredit: {
    type: Number,
    default: 0
  },
  
  // Metadata
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  postedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  notes: {
    type: String,
    trim: true
  }
}, {
  timestamps: true
});

// Compound index for company + date
journalEntrySchema.index({ company: 1, date: -1 });
journalEntrySchema.index({ company: 1, entryNumber: 1 });
journalEntrySchema.index({ company: 1, sourceType: 1, sourceId: 1 });

// Pre-save middleware to calculate totals
journalEntrySchema.pre('save', function(next) {
  // Calculate totals from lines
  this.totalDebit = this.lines.reduce((sum, line) => sum + (line.debit || 0), 0);
  this.totalCredit = this.lines.reduce((sum, line) => sum + (line.credit || 0), 0);
  next();
});

// Static method to generate entry number
journalEntrySchema.statics.generateEntryNumber = async function(companyId) {
  const today = new Date();
  const year = today.getFullYear();
  const month = String(today.getMonth() + 1).padStart(2, '0');
  const day = String(today.getDate()).padStart(2, '0');
  
  // Create a unique prefix using company ID and current date
  // This ensures uniqueness across all companies
  const companyPrefix = String(companyId).slice(-4).toUpperCase();
  
  // Find the last entry for this company (any date) to get the max sequence
  const lastEntry = await this.findOne({
    company: companyId
  }).sort({ entryNumber: -1 });
  
  let sequence = 1;
  if (lastEntry) {
    // Extract sequence from last entry and increment
    const parts = lastEntry.entryNumber.split('-');
    const lastSeq = parseInt(parts[parts.length - 1]);
    if (!isNaN(lastSeq)) {
      sequence = lastSeq + 1;
    }
  }
  
  // Use format: JE-{companyPrefix}-{yearMonthDay}-{sequence}
  return `JE-${companyPrefix}-${year}${month}${day}-${String(sequence).padStart(4, '0')}`;
};

// Method to validate debits equal credits
journalEntrySchema.methods.isBalanced = function() {
  return Math.abs(this.totalDebit - this.totalCredit) < 0.01;
};

// Static method to get trial balance
journalEntrySchema.statics.getTrialBalance = async function(companyId, startDate, endDate) {
  const query = { 
    company: companyId, 
    status: 'posted',
    date: { $gte: startDate, $lte: endDate }
  };
  
  const entries = await this.find(query);
  
  const accountBalances = {};
  
  entries.forEach(entry => {
    entry.lines.forEach(line => {
      const code = line.accountCode;
      if (!accountBalances[code]) {
        accountBalances[code] = {
          code,
          name: line.accountName,
          debit: 0,
          credit: 0,
          balance: 0
        };
      }
      
      accountBalances[code].debit += line.debit || 0;
      accountBalances[code].credit += line.credit || 0;
    });
  });
  
  // Calculate balances based on normal balance
  Object.values(accountBalances).forEach(account => {
    // This will be adjusted based on account type in the report
    account.balance = account.debit - account.credit;
  });
  
  return accountBalances;
};

const JournalEntry = mongoose.model('JournalEntry', journalEntrySchema);

module.exports = JournalEntry;
